server:
  port: '10480'
spring:
  application:
    name: demo
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/teacher_service
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 20MB # TODO
      max-request-size: 20MB # TODO
logging:
  level:
    web: DEBUG
jwt:
  secret: jdsokanfh01827ehf3whhf5nghmcnj2ghn178ooxmnsjah318oslgjmclsjghncl71jsng
  lifetime: 1h
user-files-dir: user-files
external-api-url: http://localhost:10481/